export const personalProjects = [
  {
    id: "coffedelivery",
    name: "Coffee Delivery",
    description: "lorem asfdhjuaf asofhuaosuhfoaslk",
    link: "https://coffee-delivery-ashy-eight.vercel.app/",
    image: "https://picsum.photos/400/400",
    tags: [{ titleTag: "React" }, { titleTag: "NextJS" }],
  },
  {
    id: "igniteblog",
    name: "Ignite Blog",
    description: "lorem asfdhjuaf asofhuaosuhfoaslk",
    link: "https://ignite-gitblog.vercel.app/",
    image: "https://picsum.photos/400/400",
  },
  {
    id: "coffeDelivery",
    name: "Coffee Delivery",
    description: "lorem asfdhjuaf asofhuaosuhfoaslk",
    link: "https://coffee-delivery-ashy-eight.vercel.app/",
    image: "https://picsum.photos/400/400",
  },
  {
    id: "sociallinksprofile",
    name: "Social Links Profile",
    description: "lorem asfdhjuaf asofhuaosuhfoaslk",
    link: "https://social-links-profile-nine-beta.vercel.app/",
    image: "https://picsum.photos/400/400",
  },
  {
    id: "reginaweb",
    name: "LReginaPsyWeb",
    description: "lorem asfdhjuaf asofhuaosuhfoaslk",
    link: "https://regina-psiweb.vercel.app/",
    image: "https://picsum.photos/400/400",
  },
  {
    id: "dtmoney",
    name: "DT Money",
    description: "lorem asfdhjuaf asofhuaosuhfoaslk",
    link: "https://dt-money-teal.vercel.app/",
    image: "https://picsum.photos/400/400",
  },
  {
    id: "alurakut",
    name: "Alura Orkut",
    description: "lorem asfdhjuaf asofhuaosuhfoaslk",
    link: "https://alurakut-six-liard.vercel.app/",
    image: "https://picsum.photos/400/400",
  },
  {
    id: "igniteshop",
    name: "IgniteShopping",
    description: "lorem asfdhjuaf asofhuaosuhfoaslk",
    link: "https://ignite-shop-o3oi.vercel.app/",
    image: "https://picsum.photos/400/400",
  },
  {
    id: "localizaclima",
    name: "Localiza Clima",
    description: "lorem asfdhjuaf asofhuaosuhfoaslk",
    link: "https://localiza-clima.vercel.app/",
    image: "https://picsum.photos/400/400",
  },
  {
    id: "coffeDelivery5453",
    name: "Coffee Delivery",
    description: "lorem asfdhjuaf asofhuaosuhfoaslk",
    link: "https://coffee-delivery-ashy-eight.vercel.app/",
    image: "https://picsum.photos/400/400",
  },
  {
    id: "coffeDelivery123",
    name: "Coffee Delivery",
    description: "lorem asfdhjuaf asofhuaosuhfoaslk",
    link: "https://coffee-delivery-ashy-eight.vercel.app/",
    image: "https://picsum.photos/400/400",
  },
  {
    id: "coffeDelivery43532",
    name: "Coffee Delivery",
    description: "lorem asfdhjuaf asofhuaosuhfoaslk",
    link: "https://coffee-delivery-ashy-eight.vercel.app/",
    image: "https://picsum.photos/400/400",
  },
];
